const API_BASE_URL = 'http://localhost:3000';

const TOP_100_PASSWORDS = [
    '123456', 'admin', '12345678', '123456789', '1234', '12345', 'password', '123', 'Aa123456', '1234567',
    'unknown', '1234567890', '111111', '000000', '123123', '666666', 'qwerty', 'user', '12345678', '987654321',
    '123456789', 'root', '12345678', '888888', '555555', 'password123', '654321', '123456789', '777777', '1111',
    '444444', '0000', '333333', '222222', '121212', 'sunshine', '12345678', 'p@ssword', 'guest', 'welcome',
    'football', 'monkey', 'princess', 'ashley', 'superman', 'baseball', 'michael', 'charlie', 'jennifer', 'shadow',
    'password1', '123456', 'love', 'iloveyou', '010101', '1q2w3e4r', 'secret', 'hunter2', 'google', 'login',
    'master', 'computer', 'access', 'network', 'system', 'server', 'database', 'security', 'internet', 'website',
    'service', 'account', 'profile', 'member', 'office', 'school', 'college', 'student', 'teacher', 'lesson',
    'qazwsx', 'wsxedc', 'edcrfvt', 'rfvtgb', 'tgbnhy', 'yhnujm', 'ujmikol', 'okm987', 'plm123', 'zaq123',
    'zaq1xsw2', 'cde3vfr4', 'bgt5nhy6', 'mju7nhy6', 'klo8mju7', 'nji9bgt5', 'vfr4cde3', 'xsw2zaq1', '123450', '654321'
];

const NICKNAME_SUFFIXES = ['_', 'x', 'z', 'pro', 'official', 'real', 'the', 'mr', 'ms'];

const registerForm = document.getElementById('registerForm');
const loginForm = document.getElementById('loginForm');
const phoneInput = document.getElementById('phone');
const emailInput = document.getElementById('email');
const dateOfBirthInput = document.getElementById('dateOfBirth');
const passwordInput = document.getElementById('password');
const passwordRepeatInput = document.getElementById('passwordRepeat');
const nicknameInput = document.getElementById('nickname');
const agreementCheckbox = document.getElementById('agreement');
const submitBtn = document.getElementById('submitBtn');

let nicknameAttempts = 0;
let autoGeneratedPassword = '';

async function hashPassword(password) {
    const encoder = new TextEncoder();
    const data = encoder.encode(password);
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

function formatPhoneBy(value) {
    let digits = value.replace(/\D/g, '');
    if (digits.startsWith('375')) {
        digits = digits.slice(0, 12);
    } else if (digits.startsWith('80')) {
        digits = '375' + digits.slice(2, 11);
    } else if (digits.length > 0 && !digits.startsWith('375')) {
        digits = '375' + digits.slice(0, 9);
    }

    let formatted = '';
    if (digits.length > 0) formatted = '+375';
    if (digits.length > 3) formatted += ` (${digits.slice(3, 5)}`;
    if (digits.length > 5) formatted += `) ${digits.slice(5, 8)}`;
    if (digits.length > 8) formatted += `-${digits.slice(8, 10)}`;
    if (digits.length > 10) formatted += `-${digits.slice(10, 12)}`;
    return formatted;
}

function validatePassword(password) {
    const checks = {
        length: password.length >= 8 && password.length <= 20,
        uppercase: /[A-Z]/.test(password),
        lowercase: /[a-z]/.test(password),
        number: /[0-9]/.test(password),
        special: /[!@#$%^&*()_+\-=\[\]{}|;:,.<>?]/.test(password),
        notCommon: !TOP_100_PASSWORDS.includes(password.toLowerCase())
    };

    document.getElementById('req-length').className = 'req-item ' + (checks.length ? 'valid' : 'invalid');
    document.getElementById('req-uppercase').className = 'req-item ' + (checks.uppercase ? 'valid' : 'invalid');
    document.getElementById('req-lowercase').className = 'req-item ' + (checks.lowercase ? 'valid' : 'invalid');
    document.getElementById('req-number').className = 'req-item ' + (checks.number ? 'valid' : 'invalid');
    document.getElementById('req-special').className = 'req-item ' + (checks.special ? 'valid' : 'invalid');
    document.getElementById('req-common').className = 'req-item ' + (checks.notCommon ? 'valid' : 'invalid');

    return Object.values(checks).every(Boolean);
}

function validateAge() {
    const dob = new Date(dateOfBirthInput.value);
    const today = new Date();
    let age = today.getFullYear() - dob.getFullYear();
    const m = today.getMonth() - dob.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < dob.getDate())) age--;

    const errorEl = document.getElementById('dateOfBirthError');
    if (age < 16) {
        errorEl.textContent = 'Регистрация разрешена только с 16 лет ';
        return false;
    }
    errorEl.textContent = '';
    return true;
}

document.getElementById('generateNicknameBtn').addEventListener('click', () => {
    const fName = document.getElementById('firstName').value.trim();
    const lName = document.getElementById('lastName').value.trim();

    if (!fName || !lName) {
        alert('Сначала введите Имя и Фамилию');
        return;
    }

    nicknameAttempts++;
    if (nicknameAttempts <= 5) {
        const suffix = NICKNAME_SUFFIXES[Math.floor(Math.random() * NICKNAME_SUFFIXES.length)];
        nicknameInput.value = (fName.slice(0, 2) + lName.slice(0, 3) + suffix + Math.floor(Math.random() * 99)).toLowerCase();
        document.getElementById('nicknameAttempts').textContent = `Попыток: ${nicknameAttempts}/5`;
    } else {
        nicknameInput.readOnly = false;
        nicknameInput.focus();
        document.getElementById('nicknameAttempts').textContent = 'Доступен ручной ввод';
    }
    validateForm();
});

phoneInput.addEventListener('input', (e) => {
    e.target.value = formatPhoneBy(e.target.value);
    validateForm();
});

passwordRepeatInput.addEventListener('paste', (e) => e.preventDefault()); //

document.getElementsByName('passwordMethod').forEach(radio => {
    radio.addEventListener('change', (e) => {
        const isManual = e.target.value === 'manual';
        document.getElementById('passwordManualGroup').style.display = isManual ? 'block' : 'none';
        document.getElementById('passwordAutoGroup').style.display = isManual ? 'none' : 'block';
        if (!isManual) {
            autoGeneratedPassword = Math.random().toString(36).slice(-10) + "A1!";
            document.getElementById('autoPassword').value = autoGeneratedPassword;
        }
        validateForm();
    });
});

function validateForm() {
    const isPhoneValid = phoneInput.value.replace(/\D/g, '').length === 12;
    const isEmailValid = emailInput.value.includes('@');
    const isAgeValid = dateOfBirthInput.value ? validateAge() : false;

    const isManual = document.querySelector('input[name="passwordMethod"]:checked').value === 'manual';
    const isPassValid = isManual ? (validatePassword(passwordInput.value) && passwordInput.value === passwordRepeatInput.value) : true;

    const isNameValid = document.getElementById('firstName').value.length >= 2 && document.getElementById('lastName').value.length >= 2;
    const isNickValid = nicknameInput.value.length > 0;
    const isAgreed = agreementCheckbox.checked;

    const isValid = isPhoneValid && isEmailValid && isAgeValid && isPassValid && isNameValid && isNickValid && isAgreed;
    submitBtn.disabled = !isValid;
    return isValid;
}

registerForm.addEventListener('input', validateForm);

registerForm.addEventListener('submit', async (e) => {
    e.preventDefault();
    const isManual = document.querySelector('input[name="passwordMethod"]:checked').value === 'manual';
    const finalPassword = isManual ? passwordInput.value : autoGeneratedPassword;

    const userData = {
        firstName: document.getElementById('firstName').value.trim(),
        lastName: document.getElementById('lastName').value.trim(),
        patronymic: document.getElementById('patronymic').value.trim(),
        phone: phoneInput.value.replace(/\D/g, ''),
        email: emailInput.value.trim(),
        nickname: nicknameInput.value.trim(),
        birthDate: dateOfBirthInput.value,
        password: await hashPassword(finalPassword),
        role: 'user',
        createdAt: new Date().toISOString()
    };

    try {
        const response = await fetch(`${API_BASE_URL}/users`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(userData)
        });

        if (response.ok) {
            alert('Регистрация успешно завершена!');
            window.location.href = 'index.html';
        }
    } catch (err) {
        console.error('Ошибка регистрации:', err);
    }
});

loginForm.addEventListener('submit', async (e) => {
    e.preventDefault();
    const email = document.getElementById('loginEmail').value;
    const rawPass = document.getElementById('loginPassword').value;
    const hashedPass = await hashPassword(rawPass);

    try {
        const response = await fetch(`${API_BASE_URL}/users?email=${email}&password=${hashedPass}`);
        const users = await response.json();

        if (users.length > 0) {
            localStorage.setItem('currentUser', JSON.stringify(users[0]));
            window.location.href = 'booking.html';
        } else {
            alert('Неверный email или пароль');
        }
    } catch (err) {
        console.error('Ошибка входа:', err);
    }
});

document.querySelectorAll('.auth-tab').forEach(tab => {
    tab.addEventListener('click', () => {
        document.querySelectorAll('.auth-tab').forEach(t => t.classList.remove('active'));
        document.querySelectorAll('.auth-form').forEach(f => f.classList.remove('active'));
        tab.classList.add('active');
        document.getElementById(tab.dataset.tab + 'Form').classList.add('active');
    });
});
